# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nUNMbfO0rETQNGllIosf5KMsGMpxfnCX
"""



import pandas as pd
df = pd.read_csv('/content/hobby.csv')
#df
print(df.values.tolist())

import pandas as pd
import numpy as np
df = pd.read_excel('/content/v and h stack.xlsx', header=None)
df1 = pd.read_excel('/content/v and h stack 2.xlsx', header=None)
array = df.to_numpy()
array1 = df1.to_numpy()
print(array)
print(array1)

import pandas as pd
df = pd.read_excel('/content/employee9.xlsx')
a = df
print(a.values.tolist())
df1 = pd.read_excel(r'/content/salary9.xlsx')
l = list(df1.itertuples(index=False))
t1 = [tuple(x) for x in df1.values]
d1 = df.to_dict()
def freq(l):
  counter = 0
  num = l[0]
  for i in l:
    cf = l.count(i)
    if(cf>counter):
      counter = cf
      num = i
      return 0
print(freq(l))

import csv
file =open("/content/employee.salaray.csv","r")
data=list(csv.reader(file))
data.sort()
file.close()
file1 = open("/content/employee.name.csv","r")
data1 = list(csv.reader(file1))
print(data1)
#imerging two files
data2 = []
for i in range(len(data)):
  data2.append(data[i]+data1[i])
print(data2)
print(data2[0])
#sorting as per records
data2.sort(key=lambda x: int(), reverse = True)
print(data2)
#converting list to csv file
file2 = open("/content/empty.emplyee.csv","w")
cw=csv.writer(file2)
cw.writerows(data2)
file.close()
file.close()
file.close()

import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
arr[1] = 42
arr[0] = 45
print(arr)
print(x)
print(y)

import numpy as np
x = np.array([[1,2], [4,5]])
y = np.array([[6,7], [9,10]])
print("Addition of matrix")
print(np.add(x,y))
print("Subtraction of matrix")
print(np.subtract(x,y))

l1 = np.matrix('1,2,3 ; 4,5,6 ; 7,8,9')
a = np.array(l1)
print(a)
#transpose of matrix
print(a.T)