# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dQ9B9Qz66qG6IPJ9dUabglvD8ikajFzJ
"""

a = np.vstack(array)
print(a)

b=np.hstack(array1)
print(b)

c = np.dstck(array)
print(c)