# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aJdDGcopvE2JEDHuwgOonLofx2J0jHCJ
"""

import pandas as pd
import numpy as np
df = pd.read_excel('/content/v and h stack.xlsx', header=None)
df1 = pd.read_excel('/content/v and h stack 2.xlsx', header=None)
array = df.to_numpy()
array1 = df1.to_numpy()
print(array)
print(array1)

a = np.vstack(array)
print(a)

b = np.hstack(array1)
print(b)

c = np.dstack(array1)
print(c)

array = np.random.randint(0,3,(20,20))

zeros = np.sum(array==0)
ones = np.sum(array==1)
twos = np.sum(array==2)

print(zeros)
print(ones)
print(twos)

arr_stacked = np.stack([array, array])
print('numpy horizontal stacking method #1')
print('                                   ')
print(arr_stacked)

print("Addition of matrix")
print(np.add(array,array1))

matrix_length = len(array)
print(matrix_length)

for i in range(matrix_length):
  print(array[i][-1])

print(array.T)

c = np.stack((array, array1),axis=0)
print(c)

array = array[:,array[0,:].argsort()]
print(array)

#array1 = array1[array1[:,1].argsort(kind='mergesort')]
print(array1)

array3 = array1.copy()
print(array3)