# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BseA31C9cuptplutgMai4iJLmUNGLSzq
"""

_len = input()
score_str = input()
score_list = score_str.split(' ')
score_list = [int(element) for element in score_list]
min_value = max(score_list)
max_value = min(score_list)
average = sum(score_list)/len(score_list)
print(int(min_value + max_value+ average))

_input = input()
num = list()
for element in _input:
    try:
        num.append(int(element))
    except:
        None
if sum(num) > 10:
    print(15)
elif sum(num) > 4:
    print(10)
else:
    print(5)