# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaqFM_yA2ayIVNZ3nlU3ioHV_yk1klb8
"""

import pandas as pd
df=pd.read_csv('/content/vampir.csv')
print(df)

a=df['Rollno']
b=df['Name']

df.Rollno = df.Rollno.astype('int64')
d=df['Name'][df.Rollno>2]

def student(a,b):
  print('stud:',a,b)
student(a,b)
def student(d):
  print('Student Details:',d)
student(d)