# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZsN5BJ8vVykguiBJRyZ_SamvmP2eYMvS
"""

import pandas as pd
df=pd.read_csv('/content/stationaryabjects.csv')
print(df)

#display all the data having qty greater than 54
filtered_data = df[df['quantity']>54]
print(filtered_data)

df=pd.read_csv('/content/stationaryabjects.csv')
df.loc[df['price']==10,'ratings']=10
df.to_csv('/content/stationaryabjects.csv')
print(df.to_csv)

df=pd.read_csv('/content/stationaryabjects.csv')
df=df[~df['quantity'].isin([543,788])]
print(df)