# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cwW4LB8ZuHjx5SH_zLcaRYM2qIgQrOb6
"""

print("enter a value")
num=int(input())
sum=0
i=1
while i<=num:
  sum=sum+i
  i=i+1
  print("sum",sum)

l1=["c++","java","python"]
for i in l1:
  print("loop refers to book",i)

def even():
  print("enter a number : ")
  num = int(input())
  if num%2==0:
    print("number is even:",num)
  else:
    print("number is odd:",num)
even()

a=10
b=True
c=16.55
d=[10,20,30]
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(abs(15))

l1=["","",""]
l2=["a","",""]
l3=[True,True]
l4=[True,False]
l5=[False,False]
a=all(l1)
b=all(l2)
c=all(l3)
d=all(l4)
e=all(l5)
print(a)
print(b)
print(c)
print(d)
print(e)

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_excel('')