# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DakA0Hy9LmW0vCeXm0EEPaoCG4WMutlu
"""

#Python data types
#Numbers
a=25
print("a as int : ",a)
b=548873
print("b as long : ",b)
c=14.25
print("c as float : ",c)
d=3.14j
print("d as complex : ",d)

#string
str1 = "welcome to python"
print(str1)

#list
l1 = [15,25.6,"python"]
print(l1)

#Tuple
t1 = (21,"python",21.45)
print(t1)

#dictionary
d1 = {"Aradhana" : 21, "Prarthana" : 100, "Rugved" : 23}
print(d1)

#Decision making statements
#if statement
n1 = int(input())
n2 = int(input())
n3 = int(input())
if n1>n2 and n1>n3 :
  print(n1,"is largest")
if n2>n3 and n2>n3 :
  print(n2,"is largest")
if n3>n1 and n3>n2 :
  print(n3,"is largest")

#if-else statement
print("enter a number")
num = int(input())
if num%2==0 :
  print(num,"is even")
else :
  print(num,"is odd")

#nested if else
n1 = int(input())
n2 = int(input())
n3 = int(input())
if n1>n2:
  if n1>n3:
    print(n1,"is largest")
if n2>n1:
  if n2>n3:
    print(n2,"is largest")
if n3>n1:
  if n3>n2:
    print(n3,"is largest")

#short hand if-else
print("enter any number")
num = int(input())
print(num,"is even") if num%2==0 else print(num,"is odd")

#elif
weather = input("what is the weather today?")
if weather == "Sunny":
  print("It is great day to go for picnic!")
elif weather == "Rainy":
  print("remember to bring an umbrella!")
elif weather == "Cloudy":
  print("Don't forget to bring a jacket in case it rain")
else:
  print("sorry! I don't understand that weather condition")

#append
l1 = [10,20,"Python",94.2,314]
l1.append(21)
print(l1)

#insert
l1 = ["python","java","essential of data science"]
print(l1)
l1.insert(2,"hadoop")
print(l1)

#extend
l1 = [10,20,30]
l2 = [15,35,45,55]
l1.extend(l2)
print(l1)

#statistics
import statistics
l1 = [1,3,4,5,6,6,6,6]
print(statistics.mean(l1))

#median
from statistics import median
t1 = (21,23,45,67)
print(median(t1))

#The median_low
import statistics
set1 = [1,2,3,4,5]
print("low median of the set is",(statistics.median_low(set1)))

#The median_high
import statistics
set1 = [1,3,3,4,5]
print("High median of the set is",(statistics.median_high(set1)))

#mode
from statistics import mode
t1 = (6,6,6,5,5,4,4,3,3,2,3,2,1,3)
print("mode of data set is",(mode(t1)))

#Range = largest data value-smallest data Value
arr = [1,2,3,4,5]
maximum = max(arr)
minimum = min(arr)
range = maximum-minimum
print("maximum={}, minimum={}, and range={}".format(maximum,minimum,range))

#variance
from statistics import variance
t1=(1,2,5,4,8,9,12)
print("variance of sampel is s",(variance(t1)))

#standard deviation
from statistics import stdev
s1=(1,2,3,5,7,8,12)
print("the standard deviation of sampel is s",(stdev(s1)))

#loop manipulation
i=1
while i<10:
  print("welcome")
  i=i+1

print("enter a value")
num=int(input())
sum=0
i=1
while i<=num:
  sum=sum+i
  i=i+1
  print("sum",sum)

#for loop
l1=["C++","java","python"]
for i in l1:
  print("loop refers to book",i)

#function
#1
def sayHello():
  print("welcome to python")
sayHello()

#2
def even():
  print("enter a number : ")
  num = int(input())
  if num%2==0:
    print("number is even:",num)
  else:
    print("number is odd:",num)
even()

#3
def sum():
  a=5
  b=7
  sum=a+b
  print("sum=",sum)
sum()

#4
def Loopoffruits():
  fruits = ["watermelon","pineapple","Cherry"]
  for i in fruits:
    print(i,"it is an fruits name")
Loopoffruits()

#datatype and object related function
a=10
b=True
c=16.55
d=[10,20,30]
print(type(a))
print(type(b))
print(type(c))
print(type(d))
print(abs(15))

#all
l1=["","",""]
l2=["a","",""]
l3=[True,True]
l4=[True,False]
l5=[False,False]
a=all(l1)
b=all(l2)
c=all(l3)
d=all(l4)
e=all(l5)
print(a)
print(b)
print(c)
print(d)
print(e)

#any
#1
def Bill():
  p1 = int(input())
  p2 = int(input())
  p3 = int(input())
  p4 = int(input())
  sum = p1+p2+p3+p4
  print("The total price of all products = ",sum)
Bill()

