# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_4trODJ3TbrTGXP2mSUcZiK3b5bW9UT
"""

a = 20
b = 30
if(a>b):
  print("a")
else:
  print("b")

numbers = [1,2,3,4,5]
sum = 0
for num in numbers:
  sum += num
print("The sum of the numbers is: ",sum)

numbers = [1,2,3,4,5]
for i in range(len(numbers)):
  numbers[i] -= 2
print(numbers)

num = 5
num *= 2
print("result: ",num)

x = 10
x /= 2
print(x)

num = 10
num %= 3
print("The value nof num after using the modulo assignment operator is:",num)

num = 5
num **= 3
print(num)

x = 10
x //= 3
print(x)

a = 10
b = 5
if a == b:
  print("a is equal to b")
else:
  print("a is not equal to b")

number = int(input("Enter a number: "))
if number %2 != 0:
  print(number,"is odd")
else:
  print(number, "is even")

a = 20
b = 30
if(a<b):
  print("a")
else:
  print("b")

num = int(input("Enter a number: "))
if num >=10:
  print("The number is greater than or equal to 10")
else:
  print("The number is less than 10")

import pandas as pd
df = pd.read_excel('/content/employee9.xlsx')
a = df
print(a.values.tolist())
df1 = pd.read_excel(r'/content/salary9.xlsx')
l = list(df1.itertuples(index=False))
t1 = [tuple(x) for x in df1.values]
d1 = df.to_dict()
def freq(l):
  counter = 0
  num = l[0]
  for i in l:
    cf = l.count(i)
    if(cf>counter):
      counter = cf
      num = i
      return 0
print(freq(l))

num = int(input("Enter a number: "))
if num <=10:
  print("The number is smaller than or equal to 10")
else:
  print("The number is greater than 10")

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
result = num1+num2
print("The sum of",num1,"and",num2,"is",result)

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
result = num1-num2
print("The differnce of",num1,"and",num2,"is",result)

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
result = num1*num2
print("The multiplication of",num1,"and",num2,"is",result)

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
result = num1/num2
print("The division of",num1,"and",num2,"is",result)

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
remainder = num1 % num2
print("The remainder of",num1,"divided by",num2,"is",remainder)

base = float(input("enter the base: "))
exponent = float(input("Enter the exponent: "))
result = base**exponent
print(f"{base} to the power of {exponent} is {result}")

num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
result9 = num1 // num2
print("the result of num division is",result)