# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ok9Hfs0bFzuts6mUPf2FJOzyP_3atUH5
"""

import pandas as pd
df = pd.read_csv('/content/hobby.csv')
#df
print(df.values.tolist())

a=df['hobby']
print(a)

import pandas as pd
df = pd.read_csv('/content/hobby.csv')
a = df
print(a.values.tolist())
df1 = pd.read_csv(r'/content/hobby2.csv')
l = list(df1.itertuples(index=False))
t1 = [tuple(x) for x in df1.values]
d1 = df.to_dict()
def freq(l):
  counter = 0
  num = l[0]
  for i in l:
    cf = l.count(i)
    if(cf>counter):
      counter = cf
      num = i
      return 0
print(freq(l))

import csv
file =open("/content/hobby.csv","r")
data=list(csv.reader(file))
data.sort()
file.close()
file1 = open("/content/hobby2.csv","r")
data1 = list(csv.reader(file1))
print(data1)
#imerging two files
data2 = []
for i in range(len(data)):
  data2.append(data[i]+data1[i])
print(data2)
print(data2[0])
#sorting as per records
data2.sort(key=lambda x: int(), reverse = True)
print(data2)
#converting list to csv file
file2 = open("/content/hobby3.csv","w")
cw=csv.writer(file2)
cw.writerows(data2)
file.close()
file.close()
file.close()

import pandas as pd
df=pd.read_excel('/content/hobbytoday.xlsx')
b=pd.DataFrame(df)
print(b)

import pandas as pd
df = pd.read_csv('/content/hobby.csv')
df1=pd.read_csv('/content/hobby2.csv')
c=pd.merge(df,df1)
print(c)

print([['hobby','hobby=passion']])
g=df.columns.tolist()
print(g)

z=df['name'].value_counts()
print(z)

x=df['sr.no'].value_counts()[1]
print(x)

s=df.sort_values(by='hobby',ascending=True)
print(s)