# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BuYuqNWmRRlxaxxN5TP8LP91llgK6OIq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('/content/archive (8).zip')
df3=pd.read_csv('/content/archive (9).zip')
print(df)
df1=np.array(df)
df2=np.array(df3)
xpoints = np.array(df1)
ypoints = np.array(df2)
plt.plot(xpoints,ypoints)
plt.show()

import pandas as pd
df3=pd.read_csv('/content/archive (9).zip')
print(df3)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('/content/hobby.csv')
df2 = pd.read_csv('/content/hobby.csv')
print(df)
df1=np.array(df)
print(df1)
xpoints = np.array(df1)
ypoints = np.array(df2)
plt.plot(xpoints,ypoints)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('/content/archive (8).zip')
df3=pd.read_csv('/content/archive (9).zip')
print(df)
df1=np.array(df)
df2=np.array(df3)
xpoints = np.array(df1)
ypoints = np.array(df2)
plt.plot(xpoints,ypoints)
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
excel_file_path = "/content/isha108.xlsx"

# Read the Excel file into a pandas DataFrame
data_frame = pd.read_excel(excel_file_path)

# Convert the DataFrame to a NumPy array
array_data = np.array(data_frame)

# Extract two specific columns as separate arrays
x = np.array(data_frame["started year"])
y = np.array(data_frame["id"])

# Print the entire array
print(array_data)

# Print the extracted column arrays
print(x)
print(y)

# Plot the data
plt.plot(x, y, marker="o")
plt.xlabel("started year")
plt.ylabel("id")
plt.title("Graph of Column1 vs Column2")

# Display the graph
plt.show()